
default_agent: 0
allow_sliding: false
seed: 1
scene_dataset_config_file: '/mnt/fillipo/ML/zhuofan/data/scene_datasets/hm3d/hm3d_annotated_basis.scene_dataset_config.json'
scene: null
agent_height: 1.41
agent_radius: 0.17
agent_max_climb: 0.1
cell_height: 0.05
